//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Units_display {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class SpecialSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpecialSettings defaultInstance = ((SpecialSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpecialSettings())));
        
        public static SpecialSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LinkDialogURLs {
            get {
                return ((string)(this["LinkDialogURLs"]));
            }
            set {
                this["LinkDialogURLs"] = value;
            }
        }
    }
}
